### ISSUE TITLE
Consertar hero banner do index 

### ISSUE THREAD

**Issue by marcosgabriel-smc** [marcosgabriel-smc/tem-role#34]
o nome selecionado não deve ser botão e deve ter um destaque para indicar ao usuário em qual página ele está

**Comment by meleu** [comment]
A página selecionada está ficand com o texto em branco, prejudicando visibilidade.

sugestão: deixar em vermelho

![image](https://github.com/marcosgabriel-smc/tem-role/assets/8508804/106f36d3-2a57-42e7-8594-2a5ec2fef145)

**Comment by marcosgabriel-smc** [comment]
boa mlk
