### ISSUE TITLE
popular genres com mais gêneros

### ISSUE THREAD

**Issue by meleu** [marcosgabriel-smc/tem-role#39]
@marcosgabriel-smc bota aqui no comentário dessa issue todos os gêneros que você conseguir imaginar, daí eu coloco num seed

**Comment by marcosgabriel-smc** [comment]
Grime
Afrohouse
Amapiano
Bass
Breakbeat
Dance
Deep House
Drum & Bass
Dubstep
Electro
Electronica
Funky House
Hard Dance
Hard Techno
House
Indie Dance
Jackin House
Melodic Techno
Minimal
Deep Tech
Nu Disco
Disco
Organic House
Progressive House
Psy-trance
Tech House
Peak-time
Hypnotic Tecnho
Trance
Trap
UK Garage
Hardgroove

**Comment by meleu** [comment]
vê se consegue criar uma branch a partir da master e (colocar direto no seed](https://github.com/marcosgabriel-smc/tem-role/blob/master/db/seeds.rb#L140-L151)

**Comment by meleu** [comment]
@Douglasgpassos vê se consegue adiantar essa parada aqui...

o link para o seed está no comentário acima :point_up_2:
