### ISSUE TITLE
Entender melhor o que seria a descrição do evento. 

### ISSUE THREAD

**Issue by marcosgabriel-smc** [marcosgabriel-smc/tem-role#60]
https://shotgun.live/pt-br/events/ 

Se olharmos a descrição de eventos no shotgun, normalmente é uma coisa longa e descritiva. Acho que não devemos continuar usando ela no card e em outros lugares. Somente no show do evento mesmo. 

Proponho tb a gente fazer um texto padrão e incluir em todos os eventos para fins de seed e visualização.

**Comment by meleu** [comment]
concordo que a descrição deve ficar apenas no show do evento, e não no card

**Comment by meleu** [comment]
todos de acordo
