### ISSUE TITLE
Pundit - Liberação do EventList

### ISSUE THREAD

**Issue by marcosgabriel-smc** [marcosgabriel-smc/tem-role#61]
Após a criação da lista, está dando erro no pundit, vide abaixo: 

![image](https://github.com/marcosgabriel-smc/tem-role/assets/130701516/2b96b175-31d0-43c3-bfe9-0db942806c7c)

**Comment by meleu** [comment]
resolvido nesse commit: https://github.com/marcosgabriel-smc/tem-role/commit/e35f4145b1e41842adef7b3fe3bd1331e8bc07de
